name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Set up Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          gleam-version: '1.4.1'
          
      - name: Build
        run: |
          gleam build
          # Create build directory structure for GitHub Pages
          mkdir -p build
          # Copy the built JavaScript files
          cp -r priv/static/* build/ 2>/dev/null || true
          # Copy any static assets including LFS images
          cp *.jpg build/ 2>/dev/null || true
          cp -r static/* build/ 2>/dev/null || true
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4