name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - name: Install dependencies
        run: gleam deps download
      - name: Build app
        run: gleam run -m lustre/dev build app --minify
      - name: Debug build output
        run: |
          echo "Files in priv/static after build:"
          ls -la priv/static/
          echo "All files in priv directory:"
          find priv -type f
      - name: Copy output to dist
        run: |
          mkdir -p dist
          cp index.html dist/index.html
          cp -r priv dist/priv
          echo "Files copied to dist:"
          find dist -type f
      - name: Update paths in index.html for GitHub Pages
        run: |
          # Update CSS path for GitHub Pages subpath
          sed -i 's|href="/priv/static/|href="/portfolio/priv/static/|g' dist/index.html
          # Update JS path for GitHub Pages subpath and use minified version
          sed -i 's|src="/priv/static/portfolio.mjs"|src="/portfolio/priv/static/portfolio.min.mjs"|g' dist/index.html
          # Update image paths for GitHub Pages subpath
          sed -i 's|src="/priv/static/|src="/portfolio/priv/static/|g' dist/index.html
          # Show the updated file
          echo "Updated index.html:"
          cat dist/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4